
# Book settings
title: Veri Bilimi Portfolyosu
author: Nazım ÇALIK
logo: profile.png
copyright: "2025"

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: favicon.ico
  google_analytics_id: UA-XXXXXXXX-X
  home_page_in_navbar: true
  baseurl: https://github.com/nazmclk/ds-portfolio

# Launch button settings
launch_buttons:
  notebook_interface: classic
  colab_url: https://colab.research.google.com

repository:
  url: https://github.com/nazmclk/ds-portfolio
  path_to_book: ""
  branch: master

# Add GitHub buttons to your book
html:
  use_repository_button: true
